#!/bin/bash

. opener_definitions

file="$*"

Open_by_ext(){
    eval \$open_${file#?*.} $file >/dev/null 2>&1
}

Open_by_mimetype(){
    Mimetype_open $(file -L -b --mime-type $file) $file
}

Get_handler_opts(){
awk -F '=' '$0~s {$1=""; gsub(".desktop",""); gsub(";","\n"); print $0}' s="$(file -L -b --mime-type $file)" /usr/share/applications/mimeinfo.cache
}

Handle_unknown(){
preferred=$(Get_handler_opts | AWMmenu -d -i -p "Open With:")
if [[ -z $preferred ]] ; then
echo "none selected"
exit 1
fi
mimetype=$(file -L -b --mime-type $file)
add_type="\     $mimetype) $preferred \$2 ;;"
sed -i "/#newmimes/a $add_type" opener_definitions
Open_by_mimetype
}

Open_by_ext || Open_by_mimetype || Handle_unknown
