#!/usr/bin/bash

Bootstrap(){

    echo -e "\n\tInstalling texlive"
    sudo xbps-install texlive-bin texlive-latexextra \
    && source /etc/profile \
    && sudo tlmgr install adjustbox babel-german background \
    bidi collectbox csquotes everypage filehook footmisc \
    footnotebackref framed fvextra letltxmacro ly1 mdframed \
    mweights needspace pagecolor sourcecodepro \
    sourcesanspro titling ucharcat ulem unicode-math upquote xecjk xurl zref\
    || { echo -e "\n\tfailed to install texlive" \
    && return 1; }


    echo -e "\n\tInstalling pandoc-url2cite"
    sudo npm install -g pandoc-url2cite  \
    || sudo xbps-install nodejs \
    && sudo npm install -g pandoc-url2cite \
    || { echo -e "\n \tfailed to install pandoc-url2cite" \
    && return 1; }

    echo -e "\n\tInstalling tectonic"
    sudo xbps-install tectonic \
    || { echo -e "\n \tfailed to install pandoc-url2cite" \
    && return 1; }

    echo -e "\n\tInstalling templates"
    mkdir -p ~/.local/share/pandoc/templates
    cp $PWD/templates/* ~/.local/share/pandoc/templates

return 0
}

Help(){
    echo -e "\n\tThis tool allows you to easily compile markdown documents into pdf text\
    \n\n\tUsage: [file] -option(s) \
    \n\n\tOptions: \n\t-h: print this help and exit \
    \n\t-c: path to csl file \
    \n\t-t: path to latex template \
    \n\t-b: bootstrap this helper"
}

SetTemplate(){
    if [[ -z $template ]] ; then
        template="eisvogel"
    fi
    if [[ -z $CSL ]] ; then
        CSL="~/.local/share/pandoc/templates/chicago_note.csl"
    fi
}

Convertpdf(){
    pandoc \
    --filter=pandoc-url2cite --filter=pandoc-citeproc \
    --csl ~/.local/share/pandoc/templates/chicago_note.csl \
    --pdf-engine=tectonic \
    --template $template \
    -s $file \
    -o $output.pdf \
    && return 0 || return 1
}

case $@ in
    -b) Bootstrap && exit 0;;
    -h) Help && exit 0;;
esac

while getopts c:t: flag
do
    case "${flag}" in
        c) CSL=${OPTARG};;
        t) template=${OPTARG};;
    esac
done

file=$1
if [[ -z $2 ]] ; then
base=$(basename $1)
output=${base%%.*}
else
output=$2
fi
echo -e "\n\tinput: $file \n\toutput: $output.pdf"

SetTemplate
Convertpdf