#!/bin/bash

Blkinfo(){
    for partlabel in $@ ; do
    echo "/dev/$partlabel" $(blkid -p -o value -s TYPE -s LABEL "/dev/$partlabel")
    done
}

Mounter(){
    if [[ $3 == *fat* ]] ; then
        if ! mount | grep -q $1 ; then
            mkdir -p -m 766 /mnt/$2 && \
            mount $1 /mnt/$2
        fi
    fi
    echo "mounted: $1 at $2"
}

Listen(){
while read -r line ; do
    case $line in
    *sdb:*|*sdc:*|*sdd:*|*sde:*)
    fullstring=$(Blkinfo ${line#\[*\: })
    echo "connected: $fullstring"
    Mounter $fullstring
    esac
done
}

Run(){
	dmesg -W --facility=kern | Listen > /tmp/mounter-fifo
}

mkfifo -m 0004 /tmp/mounter-fifo
Run
